version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "zindey-suite-052322"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1s7u31fu0un69"
s3_prefix = "zindey-suite-052322"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AccountTableName=\"zindey-suite-account-table\" BranchTableName=\"zindey-suite-brach-table\" BusinessTableName=\"zindey-suite-business-table\" BusinessLineTableName=\"zindey-suite-business-line-table\" ItemTableName=\"zindey-suite-item-table\" PaymentTableName=\"zindey-suite-payment-table\" PolicyTableName=\"zindey-suite-policy-table\" RoleTableName=\"zindey-suite-role-table\" WarehouseTableName=\"zindey-suite-warehouse-table\" ImagesS3BucketName=\"zindey-suite-business-bucket-052322\" ItemsS3BucketName=\"zindey-suite-items-bucket-052322\" UserPoolName=\"zindey-suite-users\""
image_repositories = []
disable_rollback = true
